"""Diagnostic plots for label distribution review.

Reads data/labels.csv (generated by labels.py) and produces two plots:

  positive_rate_by_date    -- mean(label) per day; should oscillate with the ~46d cycle
  positive_rate_by_station -- histogram of per-station positive rates; should cluster near
                              the marginal rate with no stations stuck at 0% or 100%

Usage:
    uv run python -m fuel_signal.label_viz
    uv run python -m fuel_signal.label_viz --input /tmp/labels.csv --output /tmp/plots/
"""

import pathlib

import click
import matplotlib.pyplot as plt
import pandas as pd


def plot_positive_rate_by_date(df: pd.DataFrame, ax: plt.Axes) -> None:
    daily = (
        df.groupby("price_date")["label"]
        .agg(positive_rate="mean", n_stations="count")
        .reset_index()
    )
    ax.plot(daily["price_date"], daily["positive_rate"], linewidth=0.8, color="steelblue")
    ax.axhline(df["label"].mean(), color="orange", linestyle="--", linewidth=1,
               label=f"marginal rate {df['label'].mean():.3f}")
    ax.set_title("Positive rate by date")
    ax.set_xlabel("Date")
    ax.set_ylabel("Fraction label=1 (BUY)")
    ax.legend()

    twin = ax.twinx()
    twin.fill_between(daily["price_date"], daily["n_stations"], alpha=0.15, color="grey")
    twin.set_ylabel("Stations reporting", color="grey")
    twin.tick_params(axis="y", labelcolor="grey")


def plot_positive_rate_by_station(df: pd.DataFrame, ax: plt.Axes) -> None:
    stn = (
        df.groupby("station_code")["label"]
        .agg(positive_rate="mean", n_rows="count")
        .reset_index()
    )
    ax.hist(stn["positive_rate"], bins=50, color="steelblue", edgecolor="white", linewidth=0.4)
    ax.axvline(df["label"].mean(), color="orange", linestyle="--", linewidth=1,
               label=f"marginal rate {df['label'].mean():.3f}")
    ax.set_title("Positive rate by station")
    ax.set_xlabel("Fraction label=1 (BUY)")
    ax.set_ylabel("Number of stations")
    ax.legend()

    zero_pct = (stn["positive_rate"] == 0).sum()
    one_pct = (stn["positive_rate"] == 1).sum()
    if zero_pct or one_pct:
        ax.annotate(
            f"Stuck at 0%: {zero_pct}  |  Stuck at 100%: {one_pct}",
            xy=(0.98, 0.95), xycoords="axes fraction", ha="right", fontsize=9, color="red",
        )


@click.command("label-viz")
@click.option(
    "--input", "input_path",
    default="data/labels.csv",
    show_default=True,
    help="Labels CSV produced by 'python -m fuel_signal.labels'.",
)
@click.option(
    "--output", "output_dir",
    default="data/",
    show_default=True,
    help="Directory for output PNG files.",
)
def main(input_path: str, output_dir: str) -> None:
    """Produce diagnostic plots for label distribution review."""
    src = pathlib.Path(input_path)
    if not src.exists():
        raise click.ClickException(
            f"Labels file not found: {input_path}. "
            "Run 'uv run python -m fuel_signal.labels' first."
        )

    df = pd.read_csv(src, parse_dates=["price_date"])
    n_rows = len(df)
    n_stations = df["station_code"].nunique()
    marginal = df["label"].mean()
    click.echo(f"Loaded {n_rows:,} rows, {n_stations} stations, marginal rate {marginal:.3f}")

    out = pathlib.Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(figsize=(14, 4))
    plot_positive_rate_by_date(df, ax)
    fig.tight_layout()
    date_path = out / "positive_rate_by_date.png"
    fig.savefig(date_path, dpi=150)
    plt.close(fig)
    click.echo(f"Wrote {date_path}")

    fig, ax = plt.subplots(figsize=(10, 5))
    plot_positive_rate_by_station(df, ax)
    fig.tight_layout()
    stn_path = out / "positive_rate_by_station.png"
    fig.savefig(stn_path, dpi=150)
    plt.close(fig)
    click.echo(f"Wrote {stn_path}")


if __name__ == "__main__":
    main()
